DROP TABLE IF EXISTS trade_order;

CREATE TABLE redpacket_account (
  id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id        BIGINT,
  balance_amount decimal(12, 2)
)COMMENT '红包账户表';


CREATE TABLE trade_order (
  id                BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
  self_user_id      BIGINT,
  opposite_user_id  BIGINT,
  merchant_order_no BIGINT,
  amount            DECIMAL(12, 2),
  status            VARCHAR(30),
  version           BIGINT
)COMMENT '交易订单表';


INSERT INTO trade_order (self_user_id, opposite_user_id, merchant_order_no, amount, status, version)
VALUES (123, 123, 123, 100, 'start', 0);


SELECT *
FROM trade_order;

INSERT INTO redpacket_account (user_id, balance_amount)
VALUES (123, 3000);

SELECT *
FROM redpacket_account;


#需要执行的脚本

CREATE TABLE `TCC_TRANSACTION` (
  `TRANSACTION_ID` int (11
) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar (100
) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary (32
) NOT NULL,
  `BRANCH_QUALIFIER` varbinary (32
) NOT NULL,
  ` CONTENT ` varbinary (8000
) DEFAULT NULL,
  `STATUS` int (11
) DEFAULT NULL,
  `TRANSACTION_TYPE` int (11
) DEFAULT NULL,
  `RETRIED_COUNT` int (11
) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  ` VERSION ` int (11
) DEFAULT NULL,
PRIMARY KEY (`TRANSACTION_ID`
),
UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`
)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET =utf8;


CREATE TABLE `TCC_TRANSACTION_CAP` (
  `TRANSACTION_ID` int (11
) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar (100
) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary (32
) NOT NULL,
  `BRANCH_QUALIFIER` varbinary (32
) NOT NULL,
  ` CONTENT ` varbinary (8000
) DEFAULT NULL,
  `STATUS` int (11
) DEFAULT NULL,
  `TRANSACTION_TYPE` int (11
) DEFAULT NULL,
  `RETRIED_COUNT` int (11
) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  ` VERSION ` int (11
) DEFAULT NULL,
PRIMARY KEY (`TRANSACTION_ID`
),
UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`
)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `TCC_TRANSACTION_ORD` (
  `TRANSACTION_ID` int (11
) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar (100
) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary (32
) NOT NULL,
  `BRANCH_QUALIFIER` varbinary (32
) NOT NULL,
  ` CONTENT ` varbinary (8000
) DEFAULT NULL,
  `STATUS` int (11
) DEFAULT NULL,
  `TRANSACTION_TYPE` int (11
) DEFAULT NULL,
  `RETRIED_COUNT` int (11
) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  ` VERSION ` int (11
) DEFAULT NULL,
PRIMARY KEY (`TRANSACTION_ID`
),
UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`
)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `TCC_TRANSACTION_RED` (
  `TRANSACTION_ID` int (11
) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar (100
) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary (32
) NOT NULL,
  `BRANCH_QUALIFIER` varbinary (32
) NOT NULL,
  ` CONTENT ` varbinary (8000
) DEFAULT NULL,
  `STATUS` int (11
) DEFAULT NULL,
  `TRANSACTION_TYPE` int (11
) DEFAULT NULL,
  `RETRIED_COUNT` int (11
) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  ` VERSION ` int (11
) DEFAULT NULL,
PRIMARY KEY (`TRANSACTION_ID`
),
UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`
)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE `TCC_TRANSACTION_UT` (
  `TRANSACTION_ID` int (11
) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar (100
) DEFAULT NULL,
  `GLOBAL_TX_ID` varbinary (32
) NOT NULL,
  `BRANCH_QUALIFIER` varbinary (32
) NOT NULL,
  ` CONTENT ` varbinary (8000
) DEFAULT NULL,
  `STATUS` int (11
) DEFAULT NULL,
  `TRANSACTION_TYPE` int (11
) DEFAULT NULL,
  `RETRIED_COUNT` int (11
) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  ` VERSION ` int (11
) DEFAULT NULL,
PRIMARY KEY (`TRANSACTION_ID`
),
UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`, `BRANCH_QUALIFIER`
)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;































