CREATE TABLE T_USER_ACCOUNT
(
  ID          NUMBER(16) NOT NULL,
  USER_ID     NUMBER(16),
  BALACNE     NUMBER(12, 2),
  BANK_NAME   VARCHAR2(100),
  BANK_ID     NUMBER(10),
  CREATE_TIME DATE,
  MODIFY_TIME DATE
);

COMMENT ON TABLE T_USER_ACCOUNT IS '账户表';

COMMENT ON COLUMN T_USER_ACCOUNT.ID IS '自增主键';

COMMENT ON COLUMN T_USER_ACCOUNT.USER_ID IS '用户id';

COMMENT ON COLUMN T_USER_ACCOUNT.BALACNE IS '账户余额';

COMMENT ON COLUMN T_USER_ACCOUNT.BANK_NAME IS '银行卡名';

COMMENT ON COLUMN T_USER_ACCOUNT.BANK_ID IS '银行ID';

COMMENT ON COLUMN T_USER_ACCOUNT.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN T_USER_ACCOUNT.MODIFY_TIME IS '修改时间';

ALTER TABLE T_USER_ACCOUNT
  ADD CONSTRAINT pk PRIMARY KEY (ID);
ALTER TABLE T_USER_ACCOUNT
  ADD CONSTRAINT uk UNIQUE (USER_ID);


ALTER TABLE T_USER_ACCOUNT
  DROP CONSTRAINT uk;

ALTER TABLE T_USER_ACCOUNT
  MODIFY ID NUMBER(16);

ALTER TABLE T_USER_ACCOUNT
  MODIFY USER_ID NUMBER(16);


DROP TABLE T_USER_ACCOUNT;











